Repository kubeservice-stack/kubservice-charts, pull requests merged in 2023-08, with the labels that each got.

#11 [feat] add kubeservice-cosign-webhook helm charts
  charts/kubeservice-cosign-webhook/.helmignore
  charts/kubeservice-cosign-webhook/Chart.yaml
  charts/kubeservice-cosign-webhook/README.md
  charts/kubeservice-cosign-webhook/templates/NOTES.txt
  charts/kubeservice-cosign-webhook/templates/_helpers.tpl
  charts/kubeservice-cosign-webhook/templates/certificate.yaml
  charts/kubeservice-cosign-webhook/templates/clusterrole.yaml
  charts/kubeservice-cosign-webhook/templates/clusterrolebinding.yaml
  charts/kubeservice-cosign-webhook/templates/crds/kubeservice.cn_cosignkeys.yaml
  charts/kubeservice-cosign-webhook/templates/deployment.yaml
  charts/kubeservice-cosign-webhook/templates/hpa.yaml
  charts/kubeservice-cosign-webhook/templates/ingress.yaml
  charts/kubeservice-cosign-webhook/templates/issuer.yaml
  charts/kubeservice-cosign-webhook/templates/mutatingwebhookconfiguration.yaml
  charts/kubeservice-cosign-webhook/templates/role.yaml
  charts/kubeservice-cosign-webhook/templates/rolebinding.yaml
  charts/kubeservice-cosign-webhook/templates/service.yaml
  charts/kubeservice-cosign-webhook/templates/serviceaccount.yaml
  charts/kubeservice-cosign-webhook/templates/validatingwebhookconfiguration.yaml
  charts/kubeservice-cosign-webhook/values.yaml
Labels: kind/feature, size/XL

#13 [kubeservice-custom-limitrange] add auto install crds
  charts/kubeservice-custom-limitrange/Chart.yaml
  charts/kubeservice-custom-limitrange/templates/crds/custom.cmss.com_customlimitranges.yaml
  charts/kubeservice-custom-limitrange/values.yaml
Labels: kind/feature, size/M

#16 [kubeservice-cosign-webhook] Update Charts version
  charts/kubeservice-cosign-webhook/Chart.yaml
Labels: size/XS, kind/documentation
